name: c3
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/lejard-h/c3
author: Lejard Hadrien <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.3
  
dev_dependencies:
  test: ^1.3.0
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
  